@startuml
left to right direction

actor User
node mosaik


rectangle sampling {
    User -> (Modell spezifizieren)

    User -> (Strategie wählen)

    User -> (Experiment durchführen)

    (Experiment durchführen) <- mosaik

    (Simulator\nerzeugen) .> (Experiment durchführen): includes
    (Modell\nerzeugen) .> (Experiment durchführen): includes
    (EingabeSimulator\nerzeugen) .> (Experiment durchführen): includes
    (Collector\nerzeugen) .> (Experiment durchführen): includes
}


@enduml

@startuml
:Main Admin: as Admin
(Use the application) as (Use)

User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is an example.

note right of (Use)
A note can also
be on several lines
end note

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)
@enduml